### ISSUE TITLE
some error with run dclock

### ISSUE THREAD

**Issue by arden** [ronaksoft/dclock#1]
GOROOT=C:\Go #gosetup
GOPATH=C:\Users\lenovo\go #gosetup
C:\Go\bin\go.exe build -o C:\Users\lenovo\AppData\Local\Temp\___go_build_github_com_ronaksoft_dclock_cmd_server.exe github.com/ronaksoft/dclock/cmd/server #gosetup
# github.com/valyala/tcplisten
C:\Users\lenovo\go\pkg\mod\github.com\valyala\tcplisten@v0.0.0-20161114210144-ceec8f93295a\socket_other.go:11:40: undefined: syscall.SOCK_NONBLOCK
C:\Users\lenovo\go\pkg\mod\github.com\valyala\tcplisten@v0.0.0-20161114210144-ceec8f93295a\socket_other.go:11:62: undefined: syscall.SOCK_CLOEXEC
C:\Users\lenovo\go\pkg\mod\github.com\valyala\tcplisten@v0.0.0-20161114210144-ceec8f93295a\socket_other.go:13:3: cannot use fd (type syscall.Handle) as type int in return argument

Compilation finished with exit code 2

**Comment by ehsannm** [comment]
It seems on windows we cannot reuse port, code updated to fix the issue on windows.

Thanks for report
